spring:
  application:
    name: tech-discovery-service
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 8761
# tech-dicovery-service URL : http://localhost:8761/
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false